pkgconf/pkgconf

- Makefile.am
- libpkgconf/argvsplit.c
- libpkgconf/tests/argvsplit-test.c
- tests/lib1/framework-3.pc
- tests/lib1/quotes.pc
- tests/run.sh.in
pkg-config supports .pc files containing e.g.
```
Libs: -F${libdir}/cefclient.app/Contents/Frameworks -framework 'Chromium Embedded Framework'
```
and preserves the quotes.  pkgconf should do the same.
And what the heck, a unit test for argvsplit to check its behavior in this area seemed like a good idea.
> Preserve double and single quotes in library / framework names

- tests/run.sh.in
Please also checkout what happens when module contains space at one of its components, it seems like pkgconf does not support that, maybe standard does not support this case.
```
./pkgconf --modversion '/tmp/pkgconf a/tests/lib1/foo.pc'
Package /tmp/pkgconf was not found in the pkg-config search path.
````
> tests: minor cleanups

- libpkgconf/client.c
- libpkgconf/libpkgconf.h
- libpkgconf/pkg.c
- main.c
Would it be possible to pass in the client object and some user data into the error handler?  This will help me route errors to the appropriate client object.
> pass client and user data to error handler

- libpkgconf/dependency.c
- libpkgconf/pkg.c
None of them are used.
Signed-off-by: Igor Gnatenko <ignatenko@redhat.com>
> remove dead assignments

- libpkgconf/client.c
- libpkgconf/config.h.meson
- libpkgconf/meson.build
- main.c
- meson.build
Hi
I was asked to submit this for consideration. This MR adds Meson build definitions to pgkconf. Some features:
- tested to build and install on Linux
- should work on Windows as well (including MSVC)
- shared library versioning is missing
- test suite is not run
Meson is being adopted by other low level Linux userland packages such as systemd, so it should be available in most scenarios.
> Experiment to build with Meson

- libpkgconf/stdinc.h
Fixes this build error with mingw:
...
| compilation terminated.
| In file included from ../pkgconf-1.3.7/libpkgconf/libpkgconf.h:19:0,
| from ../pkgconf-1.3.7/libpkgconf/audit.c:16:
| ../pkgconf-1.3.7/libpkgconf/stdinc.h:36:12: fatal error: BaseTsd.h: No
such file or directory
| # include <BaseTsd.h>
Signed-off-by: Maxin B. John <maxin.john@intel.com>
> stdinc.h: fix build with mingw

- Makefile.am
- configure.ac
- m4/ax_check_compile_flag.m4
This adds autoconf detection for the `-Wall` and `-std=` flags.  I am proposing as a separate PR as it adds a developer dependency on `autoconf-archive`.  If that is undesirable I can probably rework it.
> Only add warnings and std flags if supported by compiler (autoconf)

- man/pkgconf.1
pkgconf exists with 0 if all modules exist and not the other way around.
> Fix --exists description in man page

- meson.build
- meson_options.txt
kyua is sadly not trivial to build on Windows.
> meson: Add option to build without kyua for tests

- libpkgconf/pkg.c
My mistake, `pkg-config` behaves identically.
> Fix incorrect comment

- libpkgconf/client.c
- libpkgconf/pkg.c
- libpkgconf/stdinc.h
- tests/regress.sh
- tests/test_env.sh.in
This patch add support for [Haiku]. The associated port can be found at https://github.com/haikuports/haikuports/pull/2026
[Haiku]: https://www.haiku-os.org/
> libpkgconf: add support for Haiku

- man/pkgconf.1
This silences the following warnings found with mandoc's lint feature.
```  
man -Tlint pkgconf
```
```
new sentence, new line
(mdoc) A new sentence starts in the middle of a text line. Start it
on a new input line to help formatters produce correct spacing.
```
```
man: pkgconf.1:23:24: WARNING: new sentence, new line
man: pkgconf.1:42:15: WARNING: new sentence, new line
man: pkgconf.1:44:73: WARNING: new sentence, new line
man: pkgconf.1:53:63: WARNING: new sentence, new line
man: pkgconf.1:60:58: WARNING: new sentence, new line
man: pkgconf.1:69:66: WARNING: new sentence, new line
man: pkgconf.1:85:56: WARNING: new sentence, new line
man: pkgconf.1:153:7: WARNING: new sentence, new line
man: pkgconf.1:202:43: WARNING: new sentence, new line
```
https://man.openbsd.org/mandoc.1 …
> man: Silence mandoc warnings.

- man/pc.5
- man/pkgconf.1
Here are the remaining fixes for `mandoc(1)` lint warnings for the `pkgconf.1` and `pc.5` manuals.
```
man -Tlint pkgconf
```
```
skipping no-space macro
(mdoc) An input line begins with an Ns macro, or the next argument
after an Ns macro is an isolated closing delimiter. The macro is
ignored.
```
```
unusual Xr order
(mdoc) In the SEE ALSO section, an Xr macro with a lower section
number follows one with a higher number, or two Xr macros referring
to the same section are out of alphabetical order.
```
```
man: pkgconf.1:114:16: WARNING: skipping no-space macro
man: pkgconf.1:114:39: WARNING: skipping no-space macro
man: pkgconf.1:119:14: WARNING: skipping no-space macro
man: pkgconf.1:119:35: WARNING: skipping no-space macro
man: pkgconf.1:119:56: WARNING: skipping no-space macro
man: …
```
> man: Silence more mandoc warnings

- man/pkg.m4.7
These should be the last `mandoc(1)` lint warnings for pkgconf. I silenced the last two warnings by adding a zero-width space at the end so the trailing delimiters are no longer trailing.
```
man -Tlint pkg.m4
```
```
new sentence, new line
(mdoc) A new sentence starts in the middle of a text line. Start it
on a new input line to help formatters produce correct spacing.
```
```
skipping paragraph macro
In mdoc(7) documents, this happens
- at the beginning and end of sections and subsections
- right before non-compact lists and displays
- at the end of items in non-column, non-compact lists
- and for multiple consecutive paragraph macros.
In man(7) documents, it happens
- for empty P, PP, and LP macros
- for IP macros having neither head nor body arguments
- for br or sp right after SH or …
```
> man: Silence mandoc warnings for pkg.m4.7

- libpkgconf/personality.c
On Debian/Ubuntu I get:
```
CC       libpkgconf/personality.lo
libpkgconf/personality.c: In function ‘load_personality_with_path’:
libpkgconf/personality.c:195:3: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
strlcpy(pathbuf, path, sizeof pathbuf);
^~~~~~~
CC       libpkgconf/parser.lo
CCLD     libpkgconf.la
ar: `u' modifier ignored since `D' is the default (see `U')
CC       cli/pkgconf-main.o
CC       cli/pkgconf-getopt_long.o
CC       cli/pkgconf-renderer-msvc.o
CCLD     pkgconf
./.libs/libpkgconf.so: undefined reference to `strlcpy'
```
strlcpy seems to be in `<bsd/string.h>` + `-lbsd` on Debian with `libbsd-dev` installed.  But this seems to work with or without that package installed.
> use pkgconf_strlcpy

- man/pkgconf-personality.5
```
man: ./pkgconf-personality.5:97:2: WARNING: unusual Xr order: pc(5) after pkg.m4(7)
```
Reproduced with `mandoc-1.14.5`.
```
man -Tlint -l ./pkgconf-personality.5
```
> man: Silence pkgconf-personality.5 warning.

- .github/workflows/test.yml
This only builds things with meson and no tests are run.
Not sure if this is something you want, feedback/questions welcome.
It should make reviewing Windows specific changes easier since you know at least that it builds fine :)
> Add basic CI for mingw-w64 32/64 bit

- .github/workflows/test.yml
Builds and runs tests. Using Debian testing since the test framework
is only in testing right now.
> Add CI for debian+meson/autotools

- libpkgconf/pkg.c
In case the version string has no whitespace then strcspn() returns
strlen() of the input, so whitespace is only found if len != strlen.
This fixes invalid warnings when parsing version fields.
> pkgconf_pkg_parser_version_func: fix whitespace detection

- libpkgconf/path.c
To avoid a crash on some platforms (like Darwin 9) provide a buffer to
realpath(3).
Darwin 9 (last PPC target) documents realpath needs to be given a buffer
to the resolved_path argument large enough to hold PATH_MAX bytes.
With NULL argument it crashes.  Solaris makes no mention of
resolved_path to be allowed NULL, yet recent versions accept it and
malloc(3) accordingly.
Because the documentation explicitly mentions PATH_MAX being the limit
to what realpath(3) would write in resolved_path, switching to a static
buffer here doesn't limit resolution compared to dynamically allocating
a buffer by realpath(3).
While this change requires a bit more space on the stack, it avoids a
malloc/free sequence, and allows successful operation on (older)
platforms that lack support for dynamically …
> libpkgconf: path: supply buffer to realpath

- cli/main.c
On Windows, pkgconf redefines the prefix by default.
This gives the user the option to disable this behavior via an environment variable.
The benefit of an environment variable is the user can change this behavior when
using a build system such as cmake or meson, which may not expose this
parameter to the user.
> cli: add environment variable PKG_CONFIG_DONT_DEFINE_PREFIX

- configure.ac
- doc/libpkgconf-path.rst
- libpkgconf/config.h.meson
- libpkgconf/path.c
- meson.build
- tests/test_env.sh.in
This converted Unix paths to Windows paths, but all cygwin tools
work with Unix paths so this shouldn't be needed.
There is one use case if you use a cygwin pkgconf with a non-cygwin toolchain,
but pkgconf works reasonable well natively now so this shouldn't be needed
anymore and more likely leads to problems and confusion.
Both cygwin and msys have patched this out already:
* https://cygwin.com/git-cygwin-packages/?p=git/cygwin-packages/pkgconf.git;a=blob;f=pkgconf.cygport;h=e5d003f3f3dfc9e374b916974018022ad8d68852;hb=HEAD#l55
* https://github.com/msys2/MSYS2-packages/blob/a4bce0c2943109e7d06c8660d91b89065eb09bea/pkgconf/PKGBUILD#L26
> Remove usage of cygwin_conv_path() under cygwin/msys

- libpkgconf/path.c
- libpkgconf/pkg.c
The current approach was to parse the .pc and, detect the prefix, throw
everything together and at the end replace all \ with / to not produce invalid
escape sequences.
This has the problem that escaping in .pc files is ignored and no longer
possible. Also in case the prefix path has a space in it the result would be
invalid because of missing escaping.
This changes the following things:
* We no longer normalize values at the end. Instead we assume .pc files use "/"
as a directory separator or "\\\\", same format as under Unix. "\\" alone no
longer works. This shouldn't be a problem since most build tools produce .pc
files with "/" like meson, cmake, autotools.
* When injecting the prefix at runtime we convert the prefix to use "/" and
escape spaces so that in combination with the .pc …
> Rework path handling on native Windows

- man/pkgconf.1
Adds the missing `--validate` option the `pkgconf.1`.
> man: Document the --validate option.

- cli/main.c
- libpkgconf/libpkgconf.h
- libpkgconf/personality.c
Hello, I was using integrating `libpkgconf` into my project and noticed some memory wasn't being cleaned up with the help of valgrind.  I was already suspicious that there was no `_deinit` function for personality, so it was pretty easy to track down.  I'm not entirely sure this is the correct fix, because I haven't been able to determine if personality owns these resources, or if client is supposed to.  If the latter is the case, let me know and I will move my clean up code to the client deinit function.
I also added some code to close `error_msgout` if it got opened, because that was making valgrind upset too.
Since the memory was still referenced, this is not that big of an issue, but I thought I might as well make a PR.
> small memory leak fix

- libpkgconf/pkg.c
- tests/regress.sh
- tests/test_env.sh.in
Proposal to fix #213
Note: we hit this in Fedora, see [1]
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1974883
> Don't prepend sysroot_dir if pkg-config file lies outside of sysroot_dir

- meson.build
Meson allows dependencies to be compiled and built as part of the parent projects build process using a subproject systems and "wraps". This is useful for situations where dependencies are difficult to install (such as windows and macos), or where a newer version is needed, or static linking is required.
Included are two patches to allow libpkgconf to be used as a subproject dependency. There is an immediate consumer for this in [muon](https://git.sr.ht/~lattis/muon), and I will be using this functionality in [meson++](https://github.com/dcbaker/meson-plus-plus), especially since support windows and macOS is a goal for meson++.
> Add support for being used as a meson subproject

- cli/main.c
- libpkgconf/client.c
- libpkgconf/libpkgconf.h
Currently, the data pointer is `const void *`, which means that the
handler can't modify the data without casting away the constness.
> libpkgconf: remove const modifier from error_handler data pointer

- pkg.m4
Hi!
I noticed you copied `pkg.m4` from pkg-config.  The file uses the old FSF postal address.
This pull request update it to use the latest GPLv2 recommended style with URL instead, the FSF has made this change in the GPLv2 license too: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
Also this bumps the serial which is necessary for all changes (should have been done with your earlier changes too).
What do you think?
Thanks,
/Simon
> pkg.m4: Bump serial.  Use URL instead of obsolete FSF postal address.

- .github/workflows/test.yml
- meson.build
Drop mingw32 arch build, see:
https://github.com/msys2/MINGW-packages/issues/24419
> ci: enable back MSI build

- Makefile.lite
I noticed the file `libpkgconf/buffer.c` was missing from the sources in `Makefile.lite`, adding it fixed my compile errors when attempting to build a statically linked pkgconf binary.
> build: add buffer.c to SRCS in Makefile.lite
